version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Install Rust (Stable)
      - Invoke-WebRequest https://win.rustup.rs -OutFile rustup-init.exe
      - .\rustup-init.exe -y
      - RefreshEnv
      - Try { $env:PATH += ";${env:USERPROFILE}\.cargo\bin" } Catch { Write-Host "Failed to add .cargo/bin to PATH" }
      - Try { rustc --version } Catch { Write-Host "Failed to call rustc"}

      # Install yarn
      - npm install -g yarn

  pre_build:
    commands:
      # Create ./src/aws-exports.js file required for AWS Cognito
      - echo "export default {aws_cognito_region:'$AWS_REGION',aws_user_pools_id:'$AWS_COGNITO_USER_POOL_ID',aws_user_pools_web_client_id:'$AWS_COGNITO_USER_POOL_CLIENT_ID'}" > ./src/aws-exports.js
  
  build:
    commands:
      # - rustc --version
      - Try { echo ${env:USERPROFILE} } Catch { Write-Host "Failed to echo userprofile" }

      # Build changelog
      - echo "changelog=- ADD CHANGELOG" >> $CODEBUILD_SRC_DIR/GITHUB_OUTPUT

      # Install app dependencies from lockfile and build web
      - yarn install --frozen-lockfile
      - $env:RUST_BACKTRACE=1
      - yarn tauri build

  post_build:
    commands:
      - echo "Success"