version: 0.2

env:
  variables:
    RUST_BACKTRACE: "full"
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Install Rust (Stable)
      - Invoke-WebRequest https://win.rustup.rs -OutFile rustup-init.exe
      - .\rustup-init.exe -y
      - $Path += ";${env:USERPROFILE}\.cargo\bin"
      - $env:Path += ";${env:USERPROFILE}\.cargo\bin"
      - RefreshEnv
      - echo $Path
      - echo $env:Path
      - gci env:* | sort-object name
      - rustc --version
      

      # Install yarn
      - npm install -g yarn

  pre_build:
    commands:
      # Create ./src/aws-exports.js file required for AWS Cognito
      - echo "export default {aws_cognito_region:'$AWS_REGION',aws_user_pools_id:'$AWS_COGNITO_USER_POOL_ID',aws_user_pools_web_client_id:'$AWS_COGNITO_USER_POOL_CLIENT_ID'}" > ./src/aws-exports.js
  
  build:
    commands:
      # - rustc --version
      - echo $env:path

      # Build changelog
      - echo "changelog=- ADD CHANGELOG" >> $CODEBUILD_SRC_DIR/GITHUB_OUTPUT

      # Install app dependencies from lockfile and build web
      - yarn install --frozen-lockfile
      - yarn tauri build

  post_build:
    commands:
      - echo "Success"